### ISSUE TITLE
Criação Tela Chatbot

### ISSUE THREAD

**Issue by Mendes113** [Chatbot-educacional/Chatbot-educacional#3]
Criação da forma de diálogo do chatbot. Informação vinda do chatbot e opção em formato de botões abaixo, vide exemplo, https://youtu.be/M51u4zWSCYw?t=61

**Comment by matt-balda** [comment]
## Issue resolvida com a Pull Request #9
Equipe mudou a ideia central para o desenvolvimento da tela ChatBot, foi aderido a library "react-chatbot-kit" para prosseguimento.
**Desenvolvedores**: @Mendes113 @matt-balda
